Parameters:
  YamlContent:
    AssociationPropertyMetadata:
      Language: yaml
    Description:
      en: The yaml content of application.
    MinLength: 1
    Required: true
    Label:
      zh-cn: 部署应用的YAML模板内容
      en: YamlContent
    AssociationProperty: Code
    Type: String
  DefaultNamespace:
    Default: default
    Required: false
    Type: String
    Description:
      en: |-
        The default namespace for the application, default value is default.
        If a namespace is defined in yaml metadata, its priority is higher than DefaultNamespace.
        If the DefaultNamespace does not exist, ROS will automatically create it and delete it during the deletion phase.
    Label:
      zh-cn: 应用程序的默认命名空间
      en: DefaultNamespace
  ClusterId:
    AssociationProperty: ALIYUN::CS::Cluster::ClusterId
    Required: true
    Type: String
    Description:
      en: The ID of the kubernetes cluster.
    Label:
      zh-cn: 集群ID
      en: ClusterId