ClusterApplication:
  MsaResource: true
  Type: ALIYUN::CS::ClusterApplication
  Properties:
    {{&Parameters.YamlContent}}
    YamlContent: {{Indent(Parameters.YamlContent, 3)}}
    {{/}}
    {{^IsNotEmpty(Parameters.YamlContent)}}
    YamlContent: |
{{&Parameters.Namespace}}
      apiVersion: v1
      kind: Namespace
      metadata:
        name: {{Parameters.Namespace}}
        labels: {{Merge(Get(Parameters, "Namespace.Labels", {}), { app: Parameters.AppName })}}
{{/}}
      ---
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: {{Parameters.AppName}}
        namespace: {{Default(Parameters.Namespace, 'default')}}
        labels:
          app: {{Parameters.AppName}}
      spec:
        replicas: {{Default(Parameters.Replicas, 2)}}
        selector:
          matchLabels:
            app: {{Parameters.AppName}}
        template:
          metadata:
            labels: {{Merge(Get(Parameters, "Deployment.Labels", {}), { app: Parameters.AppName })}}
          spec:
            containers:
              - image: {{Parameters.Image}}
                imagePullPolicy: Always
                name: {{Parameters.AppName}}
                resources: {}
                {{&Parameters.Env}}
                env: {{Parameters.Env}}
                {{/}}
      ---
      apiVersion: v1
      kind: Service
      metadata:
        name: {{Parameters.AppName}}
        namespace: {{Default(Parameters.Namespace, 'default')}}
        labels: {{Merge(Get(Parameters, "Service.MetadataLabels", {}), { app: Parameters.AppName })}}
      spec:
        ports:
          - port: {{Parameters.Port}}
            protocol: TCP
            targetPort:  {{Parameters.Port}}
        selector:
          app: {{Parameters.AppName}}
        type: ClusterIP
    ClusterId: {{Parameters.ClusterId}}
    DefaultNamespace: {{Parameters.Namespace}}
    ValidationMode: Basic
    Stage: All
    {{/}}