Parameters:
  Region: "cn-hangzhou"
  GatewayId: gw-cu9g7dem1hkn32ee70bg
  EnvironmentId: env-cu9g82mm1hkui0vcv5eg
  GatewayName: "grpc-sae"
  Name: "basic-auth-plugin_zUaJ"
SceneProfiles:
  - DisplayName:
      zh-cn: 单机版
      en: Single Service
    Template: "templates/msa.yml"
    Parameters:
      Backend:
        Cpu: 1
        Handler: index.handler
        Memory: 4096
     
     
